### ISSUE TITLE
Failed to load type SessionAccessLevel, probably due to how datamodels where changed? 

### ISSUE THREAD

**Issue by darbdarb** [New-Project-Final-Final-WIP/HeadlessTweaks#19]
Heres the error
```
[ERROR][ResoniteModLoader] Unexpected exception initializing mod from /home/container/Headless/rml_mods/HeadlessTweaks.dll:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'HeadlessTweaks.HeadlessTweaks' threw an exception.
 ---> System.TypeLoadException: Could not load type 'SkyFrost.Base.SessionAccessLevel' from assembly 'SkyFrost.Base, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.RuntimeFieldHandle.GetValue(RtFieldInfo field, Object instance, RuntimeType fieldType, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at ResoniteModLoader.ModConfigurationDefinitionBuilder.ProcessField(FieldInfo field)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at ResoniteModLoader.ModConfigurationDefinitionBuilder.ProcessAttributes()
   at ResoniteModLoader.ResoniteMod.BuildConfigurationDefinition()
   at ResoniteModLoader.ModConfiguration.LoadConfigForMod(ResoniteMod mod)
   at ResoniteModLoader.ModLoader.InitializeMod(AssemblyFile mod)
   at ResoniteModLoader.ModLoader.LoadMods()
```

**Comment by badhaloninja** [comment]
- Is everything up to date?
- Do you already have a headless tweaks config file?
  - If so roughly how old is it
  - What is the "DefaultSessionAccessLevel" value?
 
 I am unable to replicate this on my end on linux nor windows

**Comment by darbdarb** [comment]
- I'm using net8 version of 0Harmony and headless
- No seems to not be generating one?

**Comment by darbdarb** [comment]
Turns out i didnt update the mod 👍 sorry i shall close this
